Repository woorifisa-projects-3rd/woori-zip-FE, pull requests merged in 2024-11, with the labels that each got.

#3 [SETTING] 초기 환경 세팅 #2
  README.md
  woori-zip/.gitignore
  woori-zip/README.md
  woori-zip/jsconfig.json
  woori-zip/next.config.mjs
  woori-zip/package-lock.json
  woori-zip/package.json
  woori-zip/public/file.svg
  woori-zip/public/globe.svg
  woori-zip/public/next.svg
  woori-zip/public/vercel.svg
  woori-zip/public/window.svg
  woori-zip/src/app/favicon.ico
  woori-zip/src/app/fonts/GeistMonoVF.woff
  woori-zip/src/app/fonts/GeistVF.woff
  woori-zip/src/app/globals.css
  woori-zip/src/app/layout.js
  woori-zip/src/app/loan/[id]/page.js
  woori-zip/src/app/loan/layout.js
  woori-zip/src/app/loan/page.js
  woori-zip/src/app/map/layout.js
  woori-zip/src/app/map/page.js
  woori-zip/src/app/page.js
  woori-zip/src/app/page.module.css
  woori-zip/src/app/user/layout.js
  woori-zip/src/app/user/login/page.js
  woori-zip/src/app/user/page.js
  woori-zip/src/app/user/register/page.js
  woori-zip/src/assets/audio/.gitkeep
  woori-zip/src/assets/images/.gitkeep
  woori-zip/src/assets/videos/.gitkeep
  woori-zip/src/auth/authService.js
  woori-zip/src/auth/jwtUtils.js
  woori-zip/src/hooks/MapData.js
  woori-zip/src/hooks/useAuth.js
  woori-zip/src/styles/.gitkeep
  woori-zip/src/ui/loan/LoanDetail.js
  woori-zip/src/ui/loan/LoanItem.js
  woori-zip/src/ui/loan/LoanList.js
  woori-zip/src/ui/loan/loan.module.css
  woori-zip/src/ui/map/FilterDropdown.js
  woori-zip/src/ui/map/MapMarker.js
  woori-zip/src/ui/map/MapView.js
  woori-zip/src/ui/map/Sidebar.js
  woori-zip/src/ui/map/map.module.css
  woori-zip/src/ui/user/LoginForm.js
  woori-zip/src/ui/user/RegisterForm.js
  woori-zip/src/ui/user/UserProfile.js
  woori-zip/src/ui/user/user.module.css
  woori-zip/src/utils/authHelpers.js
  woori-zip/src/utils/fetchLoans.js
  woori-zip/src/utils/fetchLocations.js
  woori-zip/src/utils/mapHelpers.js
Labels: ⚙ Setting

#14 [FEAT] 대출페이지 퍼블리싱 #4
  woori-zip/src/components/domains/loan/BackCard.css
  woori-zip/src/components/domains/loan/BackCard.js
  woori-zip/src/components/domains/loan/BottomCard.css
  woori-zip/src/components/domains/loan/BottomCard.js
  woori-zip/src/components/domains/loan/CardList.css
  woori-zip/src/components/domains/loan/CardList.js
  woori-zip/src/components/domains/loan/CheckList.css
  woori-zip/src/components/domains/loan/CheckList.js
  woori-zip/src/components/domains/loan/Detail.css
  woori-zip/src/components/domains/loan/Detail.js
  woori-zip/src/components/domains/loan/LoanCheckListPage.js
  woori-zip/src/components/domains/loan/LoanDetail.js
  woori-zip/src/components/domains/loan/LoanDetailPage.js
  woori-zip/src/components/domains/loan/LoanItem.js
  woori-zip/src/components/domains/loan/LoanList.js
  woori-zip/src/components/domains/loan/LoanRecommendationPage.js
  woori-zip/src/components/domains/loan/TrueFalseButton.css
  woori-zip/src/components/domains/loan/TrueFalseButton.js
  woori-zip/src/components/domains/loan/WideCard.css
  woori-zip/src/components/domains/loan/WideCard.js
  woori-zip/src/components/domains/loan/WideCardButton.css
  woori-zip/src/components/domains/loan/WideCardButton.js
  woori-zip/src/components/domains/loan/loan.module.css
Labels: ✨ Feature

#18 [SETTING/#17]: 초기 병합
  .github/workflows/git-push.yaml
  build.sh
  woori-zip/src/app/api/health-check/route.js
Labels: ⚙ Setting

#24 [FIX] : 대출추천페이지 디자인수정 #4
  woori-zip/src/app/loan/loanRecommendation/page.js
  woori-zip/src/components/domains/loan/loanRecommendation/BackCard.css
  woori-zip/src/components/domains/loan/loanRecommendation/BottomCard.css
  woori-zip/src/components/domains/loan/loanRecommendation/CardList.css
  woori-zip/src/components/domains/loan/loanRecommendation/WideCard.css
  woori-zip/src/components/domains/loan/loanRecommendation/WideCard.js
  woori-zip/src/components/domains/loan/loanRecommendation/WideCardButton.css
Labels: ✨ Feature

#26 [FEAT/#22]: 지도 페이지 초기 구조
  woori-zip/public/images/map/apartment.png
  woori-zip/public/images/map/house.png
  woori-zip/public/images/map/officetel.png
  woori-zip/public/images/map/oneroom.png
  woori-zip/public/images/map/test.png
  woori-zip/src/app/map/layout.js
  woori-zip/src/app/map/page.js
  woori-zip/src/components/domains/map/CategoryMenu.js
  woori-zip/src/components/domains/map/CategoryMenu.module.css
  woori-zip/src/components/domains/map/FilterDropdown.js
  woori-zip/src/components/domains/map/MapMarker.js
  woori-zip/src/components/domains/map/MapView.js
  woori-zip/src/components/domains/map/NavBar.js
  woori-zip/src/components/domains/map/NavBar.module.css
  woori-zip/src/components/domains/map/PropertyList.js
  woori-zip/src/components/domains/map/PropertyList.module.css
  woori-zip/src/components/domains/map/Sidebar.js
  woori-zip/src/components/domains/map/Sidebar.module.css
  woori-zip/src/components/domains/map/map.module.css
  woori-zip/src/components/domains/map/mapView.module.css
Labels: ✨ Feature

#30 [BUG/#29]: 불필요한 이미지 제거
  woori-zip/public/images/Graph.png
  woori-zip/public/images/House.png
  woori-zip/public/images/Officetel.png
  woori-zip/public/images/Oneroom.png
  woori-zip/public/images/apartment.jpg
Labels: 🐞 Bug

#34 [FIX] : module.css 적용 #4
  woori-zip/src/components/domains/loan/loanCheckList/CheckList.js
  woori-zip/src/components/domains/loan/loanCheckList/CheckList.module.css
  woori-zip/src/components/domains/loan/loanCheckList/TrueFalseButton.js
  woori-zip/src/components/domains/loan/loanCheckList/TrueFalseButton.module.css
  woori-zip/src/components/domains/loan/loanDetail/Detail.js
  woori-zip/src/components/domains/loan/loanDetail/Detail.module.css
  woori-zip/src/components/domains/loan/loanRecommendation/BackCard.css
  woori-zip/src/components/domains/loan/loanRecommendation/BackCard.js
  woori-zip/src/components/domains/loan/loanRecommendation/BackCard.module.css
  woori-zip/src/components/domains/loan/loanRecommendation/BottomCard.js
  woori-zip/src/components/domains/loan/loanRecommendation/BottomCard.module.css
  woori-zip/src/components/domains/loan/loanRecommendation/CardList.css
  woori-zip/src/components/domains/loan/loanRecommendation/CardList.js
  woori-zip/src/components/domains/loan/loanRecommendation/CardList.module.css
  woori-zip/src/components/domains/loan/loanRecommendation/WideCard.js
  woori-zip/src/components/domains/loan/loanRecommendation/WideCard.module.css
  woori-zip/src/components/domains/loan/loanRecommendation/WideCardButton.css
  woori-zip/src/components/domains/loan/loanRecommendation/WideCardButton.js
  woori-zip/src/components/domains/loan/loanRecommendation/WideCardButton.module.css
Labels: 🐞 Bug

#36 [Feat/#23] login agreement register page
  woori-zip/public/images/bankLogo.png
  woori-zip/public/images/check.png
  woori-zip/public/images/loading.png
  woori-zip/public/images/success.png
  woori-zip/public/images/unCheck.png
  woori-zip/src/app/user/bankinglogin/page.js
  woori-zip/src/app/user/intro/page.js
  woori-zip/src/app/user/loading/page.js
  woori-zip/src/components/atoms/Tab.js
  woori-zip/src/components/domains/user/bankinglogin/BankLoginPage.js
  woori-zip/src/components/domains/user/bankinglogin/BankLoginPage.module.css
  woori-zip/src/components/domains/user/intro/LoginIntro.js
  woori-zip/src/components/domains/user/intro/LoginIntro.module.css
  woori-zip/src/components/domains/user/loading/Loading.js
  woori-zip/src/components/domains/user/loading/Loading.module.css
  woori-zip/src/components/domains/user/login/Login.js
  woori-zip/src/components/domains/user/login/Login.module.css
  woori-zip/src/components/domains/user/login/LoginPage.js
  woori-zip/src/components/domains/user/login/SubmitButton.js
  woori-zip/src/components/domains/user/login/loginPage.module.css
  woori-zip/src/components/domains/user/login/validation.js
  woori-zip/src/components/domains/user/register/Register.module.css
  woori-zip/src/components/domains/user/register/RegisterPage.js
Labels: ✨ Feature

#39 [feat/#23]: 로그인 스타일 변경
  woori-zip/src/app/login/page.js
  woori-zip/src/app/page.js
  woori-zip/src/app/user/home/page.js
  woori-zip/src/app/user/login/page.js
  woori-zip/src/app/user/register/page.js
  woori-zip/src/components/domains/loan/loanCheckList/CheckList.js
  woori-zip/src/components/domains/user/Login.module.css
  woori-zip/src/components/domains/user/LoginForm.js
  woori-zip/src/components/domains/user/Register.module.css
  woori-zip/src/components/domains/user/RegisterForm.js
  woori-zip/src/components/domains/user/login/LoginPage.js
  woori-zip/src/components/domains/user/user.module.css
Labels: ✨ Feature, 🐞 Bug

#42 [BUG/#38]: 지도 페이지 버그 수정
  woori-zip/next.config.mjs
  woori-zip/src/components/domains/map/NavBar.js
  woori-zip/src/components/domains/user/login/SubmitButton.js
Labels: 🐞 Bug, 🌏 Deploy

#43 [Merge] 메인페이지에 병합
  woori-zip/next.config.mjs
  woori-zip/public/images/bankLogo.png
  woori-zip/public/images/check.png
  woori-zip/public/images/loading.png
  woori-zip/public/images/success.png
  woori-zip/public/images/unCheck.png
  woori-zip/src/app/login/page.js
  woori-zip/src/app/page.js
  woori-zip/src/app/user/bankinglogin/page.js
  woori-zip/src/app/user/home/page.js
  woori-zip/src/app/user/intro/page.js
  woori-zip/src/app/user/loading/page.js
  woori-zip/src/app/user/login/page.js
  woori-zip/src/app/user/register/page.js
  woori-zip/src/components/atoms/Tab.js
  woori-zip/src/components/domains/loan/loanCheckList/CheckList.js
  woori-zip/src/components/domains/loan/loanCheckList/CheckList.module.css
  woori-zip/src/components/domains/loan/loanCheckList/TrueFalseButton.js
  woori-zip/src/components/domains/loan/loanCheckList/TrueFalseButton.module.css
  woori-zip/src/components/domains/loan/loanDetail/Detail.js
  woori-zip/src/components/domains/loan/loanDetail/Detail.module.css
  woori-zip/src/components/domains/loan/loanRecommendation/BackCard.css
  woori-zip/src/components/domains/loan/loanRecommendation/BackCard.js
  woori-zip/src/components/domains/loan/loanRecommendation/BackCard.module.css
  woori-zip/src/components/domains/loan/loanRecommendation/BottomCard.js
  woori-zip/src/components/domains/loan/loanRecommendation/BottomCard.module.css
  woori-zip/src/components/domains/loan/loanRecommendation/CardList.css
  woori-zip/src/components/domains/loan/loanRecommendation/CardList.js
  woori-zip/src/components/domains/loan/loanRecommendation/CardList.module.css
  woori-zip/src/components/domains/loan/loanRecommendation/WideCard.js
  woori-zip/src/components/domains/loan/loanRecommendation/WideCard.module.css
  woori-zip/src/components/domains/loan/loanRecommendation/WideCardButton.css
  woori-zip/src/components/domains/loan/loanRecommendation/WideCardButton.js
  woori-zip/src/components/domains/loan/loanRecommendation/WideCardButton.module.css
  woori-zip/src/components/domains/map/NavBar.js
  woori-zip/src/components/domains/user/bankinglogin/BankLoginPage.js
  woori-zip/src/components/domains/user/bankinglogin/BankLoginPage.module.css
  woori-zip/src/components/domains/user/intro/LoginIntro.js
  woori-zip/src/components/domains/user/intro/LoginIntro.module.css
  woori-zip/src/components/domains/user/loading/Loading.js
  woori-zip/src/components/domains/user/loading/Loading.module.css
  woori-zip/src/components/domains/user/login/Login.js
  woori-zip/src/components/domains/user/login/Login.module.css
  woori-zip/src/components/domains/user/login/LoginPage.js
  woori-zip/src/components/domains/user/login/SubmitButton.js
  woori-zip/src/components/domains/user/login/loginPage.module.css
  woori-zip/src/components/domains/user/login/validation.js
  woori-zip/src/components/domains/user/register/Register.module.css
  woori-zip/src/components/domains/user/register/RegisterPage.js
  woori-zip/src/components/domains/user/user.module.css
Labels: 🌏 Deploy

#44 [BUG/#38] 배포시 생기는 오류 파일 이름 변경
  woori-zip/src/components/domains/user/login/LoginPage.module.css
Labels: 🚨 Hotfix

#46 [Hotfix/#45] 파일 이름으로 인한 긴급 수정
  woori-zip/src/components/domains/user/login/LoginPage.js
  woori-zip/src/components/domains/user/login/LoginPage.module.css
Labels: 🚨 Hotfix

#49 [hotfix/#45] 파일명으로 인한 긴급 추가
  woori-zip/src/components/domains/user/login/LoginPage.js
  woori-zip/src/components/domains/user/login/LoginPage.module.css
Labels: 🚨 Hotfix

#50 [hotfix/#45] 파일명으로 인한 긴급 추가
  woori-zip/src/components/domains/user/login/LoginPage.js
  woori-zip/src/components/domains/user/login/LoginPage.module.css
Labels: 🚨 Hotfix

#51 [Hotfix/#45] fix name bug
  woori-zip/src/components/domains/user/login/LoginPage.js
  woori-zip/src/components/domains/user/login/SubmitButton.js
  woori-zip/src/components/domains/user/login/loginPage.module.css
Labels: 🚨 Hotfix

#67 [FEAT] 지도 페이지 데이터 정리 병합
  woori-zip/package-lock.json
  woori-zip/package.json
  woori-zip/src/app/map/page.js
  woori-zip/src/components/domains/map/CategoryMenu.js
  woori-zip/src/components/domains/map/CategoryMenu.module.css
  woori-zip/src/components/domains/map/Latitude.js
  woori-zip/src/components/domains/map/MapView.js
  woori-zip/src/components/domains/map/MobileHeader.js
  woori-zip/src/components/domains/map/MobileHeader.module.css
  woori-zip/src/components/domains/map/NavBar.js
  woori-zip/src/components/domains/map/NavBar.module.css
  woori-zip/src/components/domains/map/RangeSlider.js
  woori-zip/src/components/domains/map/RangeSlider.module.css
  woori-zip/src/components/domains/map/Sidebar.js
  woori-zip/src/components/domains/map/Sidebar.module.css
  woori-zip/src/utils/urlHelper.js
Labels: ✨ Feature

#78 [MERGE] 지도 페이지 마커 커스텀화
  woori-zip/public/icons/facility-icon.svg
  woori-zip/public/icons/icon-marker.svg
  woori-zip/src/app/map/page.js
  woori-zip/src/components/domains/map/CategoryMenu.js
  woori-zip/src/components/domains/map/MapView.js
  woori-zip/src/components/domains/map/NavBar.js
  woori-zip/src/components/domains/map/PropertyDetails.module.css
  woori-zip/src/components/domains/map/PropertyList.js
  woori-zip/src/components/domains/map/PropertyList.module.css
Labels: ✨ Feature

#80 Feat/#75 login register design
  woori-zip/src/app/user/agreement/page.js
  woori-zip/src/app/user/bankinglogin/page.js
  woori-zip/src/app/user/intro/page.js
  woori-zip/src/app/user/loading/page.js
  woori-zip/src/app/user/login/page.js
  woori-zip/src/app/user/register/page.js
  woori-zip/src/components/domains/user/agreement/AgreementPage.js
  woori-zip/src/components/domains/user/agreement/AgreementPage.module.css
  woori-zip/src/components/domains/user/bankinglogin/BankLoginPage.js
  woori-zip/src/components/domains/user/bankinglogin/BankLoginPage.module.css
  woori-zip/src/components/domains/user/intro/LoginIntro.js
  woori-zip/src/components/domains/user/intro/LoginIntro.module.css
  woori-zip/src/components/domains/user/loading/Loading.js
  woori-zip/src/components/domains/user/loading/Loading.module.css
  woori-zip/src/components/domains/user/login/Login.module.css
  woori-zip/src/components/domains/user/login/LoginIntro.js
  woori-zip/src/components/domains/user/login/LoginIntro.module.css
  woori-zip/src/components/domains/user/login/LoginPage.js
  woori-zip/src/components/domains/user/login/LoginPage.module.css
  woori-zip/src/components/domains/user/login/Tab.js
  woori-zip/src/components/domains/user/login/Tab.module.css
  woori-zip/src/components/domains/user/login/validation.js
  woori-zip/src/components/domains/user/register/Register.module.css
  woori-zip/src/components/domains/user/register/RegisterIntro.js
  woori-zip/src/components/domains/user/register/RegisterPage.js
  woori-zip/src/components/domains/user/register/RegisterWrapper.module.css
Labels: ✨ Feature

#81 [MERGE] 지도 페이지 이펙트 수정
  woori-zip/src/app/api/map/houseApi.js
  woori-zip/src/app/map/page.js
  woori-zip/src/components/domains/map/CategoryMenu.js
  woori-zip/src/components/domains/map/CategoryMenu.module.css
  woori-zip/src/components/domains/map/MapView.js
  woori-zip/src/components/domains/map/NavBar.js
  woori-zip/src/components/domains/map/PropertyList.js
  woori-zip/src/components/domains/map/Sidebar.js
  woori-zip/src/components/domains/map/Sidebar.module.css
Labels: ♻️ Refactor

#83 [FEAT] 대출페이지 API 연결 #77
  woori-zip/package-lock.json
  woori-zip/src/app/api/instance.js
  woori-zip/src/app/loan/loanCheckList/page.js
  woori-zip/src/app/loan/loanDetail/[loanGoodsId]/page.js
  woori-zip/src/app/loan/loanDetail/page.js
  woori-zip/src/app/loan/loanRecommendation/page.js
  woori-zip/src/components/domains/loan/api/loanAPI.js
  woori-zip/src/components/domains/loan/loanCheckList/CheckList.js
  woori-zip/src/components/domains/loan/loanCheckList/CheckList.module.css
  woori-zip/src/components/domains/loan/loanCheckList/TrueFalseButton.js
  woori-zip/src/components/domains/loan/loanCheckList/TrueFalseButton.module.css
  woori-zip/src/components/domains/loan/loanCheckList/WebViewLoanCheckList.js
  woori-zip/src/components/domains/loan/loanCheckList/WebViewLoanCheckList.module.css
  woori-zip/src/components/domains/loan/loanDetail/Detail.js
  woori-zip/src/components/domains/loan/loanDetail/Detail.module.css
  woori-zip/src/components/domains/loan/loanDetail/WebViewLoanDetail.js
  woori-zip/src/components/domains/loan/loanDetail/WebViewLoanDetail.module.css
  woori-zip/src/components/domains/loan/loanRecommendation/BackCard.js
  woori-zip/src/components/domains/loan/loanRecommendation/BackCard.module.css
  woori-zip/src/components/domains/loan/loanRecommendation/BottomCard.js
  woori-zip/src/components/domains/loan/loanRecommendation/BottomCard.module.css
  woori-zip/src/components/domains/loan/loanRecommendation/CardList.js
  woori-zip/src/components/domains/loan/loanRecommendation/CardList.module.css
  woori-zip/src/components/domains/loan/loanRecommendation/WebViewLoanRecommendation.js
  woori-zip/src/components/domains/loan/loanRecommendation/WebViewLoanRecommendation.module.css
  woori-zip/src/components/domains/loan/loanRecommendation/WideCard.js
  woori-zip/src/components/domains/loan/loanRecommendation/WideCard.module.css
  woori-zip/src/components/domains/loan/loanRecommendation/WideCardButton.js
Labels: ✨ Feature

#90 [REFACTOR] 지도 페이지 nav bar 버튼 수정
  woori-zip/src/app/globals.css
  woori-zip/src/app/layout.js
  woori-zip/src/components/domains/loan/loanRecommendation/CardList.module.css
  woori-zip/src/components/domains/main/PropertyCard/PropertyCard.module.css
  woori-zip/src/components/domains/main/PropertyGrid/PropertyGrid.js
  woori-zip/src/components/domains/main/PropertyGrid/PropertyGrid.module.css
  woori-zip/src/components/domains/map/NavBar.js
  woori-zip/src/components/domains/map/NavBar.module.css
  woori-zip/src/components/domains/map/PropertyList.module.css
  woori-zip/src/components/domains/map/RangeSlider.js
  woori-zip/src/components/domains/map/RangeSlider.module.css
  woori-zip/src/components/domains/map/Sidebar.module.css
Labels: ♻️ Refactor

#96 [REFACTOR] 지도 페이지 API 분리 #95
  woori-zip/src/app/api/instance.js
  woori-zip/src/app/api/map/houseApi.js
  woori-zip/src/app/map/page.js
  woori-zip/src/components/domains/map/CategoryMenu.js
  woori-zip/src/components/domains/map/NavBar.js
  woori-zip/src/components/domains/map/PropertyList.js
Labels: ♻️ Refactor

#98 [REFACTOR] 메인 페이지 라우터 연결 #97
  woori-zip/next.config.mjs
  woori-zip/src/app/map/page.js
  woori-zip/src/components/domains/main/PropertyGrid/PropertyGrid.js
  woori-zip/src/components/domains/map/Latitude.js
  woori-zip/src/components/domains/map/MapView.js
  woori-zip/src/components/domains/map/NavBar.js
  woori-zip/src/components/domains/map/PropertyDetails.js
  woori-zip/src/components/domains/map/PropertyList.js
Labels: ♻️ Refactor

#101 [FEAT] 온보딩
  woori-zip/src/app/user/(onboarding)/layout.js
  woori-zip/src/app/user/(onboarding)/layout.module.css
  woori-zip/src/app/user/(onboarding)/login/page.js
  woori-zip/src/app/user/(onboarding)/register/page.js
  woori-zip/src/app/user/(onboarding)/signup/page.js
  woori-zip/src/app/user/layout.js
  woori-zip/src/app/user/login/page.js
  woori-zip/src/app/user/register/page.js
  woori-zip/src/components/domains/user/agreement/AgreementPage.js
  woori-zip/src/components/domains/user/agreement/AgreementPage.module.css
  woori-zip/src/components/domains/user/login/LoginAdminPage.js
  woori-zip/src/components/domains/user/login/LoginAgentPage.js
  woori-zip/src/components/domains/user/login/LoginIntro.js
  woori-zip/src/components/domains/user/login/LoginIntro.module.css
  woori-zip/src/components/domains/user/login/LoginPage.module.css
  woori-zip/src/components/domains/user/login/Tab.js
  woori-zip/src/components/domains/user/login/Tab.module.css
  woori-zip/src/components/domains/user/login/validation.js
  woori-zip/src/components/domains/user/onboarding/ContentBox.js
  woori-zip/src/components/domains/user/onboarding/ContentBox.module.css
  woori-zip/src/components/domains/user/onboarding/MockupBox.js
  woori-zip/src/components/domains/user/onboarding/MockupBox.module.css
  woori-zip/src/components/domains/user/onboarding/OnboardingBox.js
  woori-zip/src/components/domains/user/onboarding/OnboardingBox.module.css
  woori-zip/src/components/domains/user/register/Register.module.css
  woori-zip/src/components/domains/user/register/RegisterPage.js
  woori-zip/src/components/domains/user/registerIntro/ContentBox.js
  woori-zip/src/components/domains/user/registerIntro/ContentBox.module.css
  woori-zip/src/components/domains/user/registerIntro/RegeterIntro.js
  woori-zip/src/components/domains/user/signup/ContentBox.js
  woori-zip/src/components/domains/user/signup/ContentBox.module.css
  woori-zip/src/components/domains/user/signup/SignupIntro.js
Labels: ✨ Feature

#102 Feat/#100 onboarding
  woori-zip/src/components/domains/user/agreement/AgreementPage.module.css
  woori-zip/src/components/domains/user/login/LoginAdminPage.js
  woori-zip/src/components/domains/user/login/LoginAgentPage.js
  woori-zip/src/components/domains/user/login/LoginIntro.module.css
  woori-zip/src/components/domains/user/login/LoginPage.module.css
  woori-zip/src/components/domains/user/login/Tab.js
  woori-zip/src/components/domains/user/login/Tab.module.css
  woori-zip/src/components/domains/user/register/RegisterPage.js
Labels: ✨ Feature

#108 [FEAT] 소비패턴분석 api 데이터 패칭 #104
  woori-zip/src/app/analysis/page.js
  woori-zip/src/app/api/analysis/analysisAPI.js
  woori-zip/src/app/api/instance.js
  woori-zip/src/components/domains/analysis/analysis/Analysis.js
  woori-zip/src/components/domains/analysis/chat/Chat.js
Labels: ✨ Feature

#110 [feat] 가입하기 수정
  woori-zip/src/components/domains/user/login/validation.js
  woori-zip/src/components/domains/user/register/Register.module.css
  woori-zip/src/components/domains/user/register/RegisterPage.js
Labels: ✨ Feature

#112 [feat] 마이페이지 북마크 api 수정
  woori-zip/src/app/api/instance.js
  woori-zip/src/app/api/mypage/BookMarkAPI.js
Labels: ✨ Feature

#117 Feat/#113 마이페이지 정보 불러오기
  woori-zip/src/app/api/mypage/MypageAPI.js
  woori-zip/src/components/domains/mypage/MemberInfo/Member.js
  woori-zip/src/components/domains/mypage/MemberInfo/Member.module.css
Labels: ✨ Feature
