Repository woorifisa-projects-3rd/woori-zip-FE, pull requests merged in 2024-12, with the labels that each got.

#119 [Feat] 지도페이지 - 소비패턴 분석 페이지 연결 초안
  woori-zip/public/data/seoul_districts_dong_data.json
  woori-zip/src/app/api/analysis/analysisAPI.js
  woori-zip/src/app/map/page.js
  woori-zip/src/components/domains/analysis/analysis/Analysis.js
  woori-zip/src/components/domains/main/PropertyGrid/PropertyGrid.js
  woori-zip/src/components/domains/map/MapView.js
  woori-zip/src/components/domains/map/NavBar.js
Labels: ✨ Feature

#122 [refactor/#121]: api 구조 변경 data안에서 가져오기
  woori-zip/src/app/api/map/houseApi.js
Labels: ♻️ Refactor

#123 [FEAT] 관리자 페이지 api 연결
  woori-zip/src/app/api/manager/managerAPI.js
  woori-zip/src/app/manager/page.js
  woori-zip/src/components/domains/analysis/analysis/Analysis.module.css
  woori-zip/src/components/domains/manager/LoanManagement/LoanView.js
  woori-zip/src/components/domains/manager/LoanManagement/LoanView.module.css
  woori-zip/src/components/domains/manager/LogManagement/LogSearch.js
  woori-zip/src/components/domains/manager/LogManagement/LogSearch.module.css
  woori-zip/src/components/domains/manager/Tabs/Tabs.module.css
  woori-zip/src/components/domains/manager/userManagement/AgentList/AgentList.js
  woori-zip/src/components/domains/manager/userManagement/AgentList/AgentList.module.css
  woori-zip/src/components/domains/manager/userManagement/ManagerList/ManagerList.js
  woori-zip/src/components/domains/manager/userManagement/ManagerList/ManagerList.module.css
  woori-zip/src/components/domains/manager/userManagement/MembersList/MembersList.js
  woori-zip/src/components/domains/manager/userManagement/MembersList/MembersList.module.css
Labels: ✨ Feature

#125 [FEAT] 로그인 연결
  woori-zip/package-lock.json
  woori-zip/package.json
  woori-zip/src/app/actions/authActions.js
  woori-zip/src/app/api/[...nextauth]/route.js
  woori-zip/src/app/api/authApi.js
  woori-zip/src/app/api/instance.js
  woori-zip/src/app/api/oauthRedirect/route.js
  woori-zip/src/app/layout.js
  woori-zip/src/app/page.js
  woori-zip/src/app/user/(onboarding)/login/page.js
  woori-zip/src/auth.js
  woori-zip/src/components/domains/user/login/LoginAdminPage.js
  woori-zip/src/components/domains/user/login/LoginIntro.js
  woori-zip/src/components/layout/Header/Header.js
Labels: ✨ Feature

#128 [FEAT] 대출체크리스트삭제 #106 (#127)
  woori-zip/src/app/api/loan/loanAPI.js
  woori-zip/src/app/loan/loanCheckList/page.js
  woori-zip/src/app/loan/loanRecommendation/page.js
  woori-zip/src/components/domains/loan/loanCheckList/CheckList.js
  woori-zip/src/components/domains/loan/loanCheckList/CheckList.module.css
  woori-zip/src/components/domains/loan/loanCheckList/WebViewLoanCheckList.js
  woori-zip/src/components/domains/loan/loanCheckList/WebViewLoanCheckList.module.css
Labels: 🌏 Deploy

#129 [DEPLOY] 배포를 위한 page.js 수정
  woori-zip/src/app/analysis/page.js
  woori-zip/src/app/map/page.js
  woori-zip/src/components/domains/mypage/Bookmarks/BookMarkCard.js
Labels: 🌏 Deploy

#132 [DEPLOY] 배포를 위한 소비패턴 분석페이지 컴포넌트 분할
  woori-zip/src/app/analysis/page.js
  woori-zip/src/components/domains/analysis/analysis/AnalysisDataLoader.js
Labels: 🌏 Deploy

#137 [DEPLOY] 배포를 위한 회원가입 컴포넌트 Suspense 추가
  woori-zip/src/app/user/(onboarding)/login/page.js
  woori-zip/src/app/user/(onboarding)/register/page.js
  woori-zip/src/components/domains/user/login/LoginContent.js
Labels: 🌏 Deploy

#139 [DEPLOY] LoginContent.js Suspense 추가
  woori-zip/src/components/domains/user/login/LoginContent.js
Labels: ✨ Feature, 🌏 Deploy

#141 [DEPLOY] LoginIntro.js Suspense 제거
  woori-zip/src/components/domains/user/login/LoginContent.js
  woori-zip/src/components/domains/user/login/LoginIntro.js
Labels: ✨ Feature, 📃 Docs

#143 [DEPLOY] Login수정
  woori-zip/src/components/domains/user/login/LoginContent.js
  woori-zip/src/components/domains/user/login/LoginIntro.js
Labels: ✨ Feature, 🌏 Deploy

#144 [DEPLOY] Login수정
  woori-zip/src/components/domains/user/login/LoginContent.js
  woori-zip/src/components/domains/user/login/LoginIntro.js
Labels: ✨ Feature, 🌏 Deploy

#145 [DEPLOY] Register 부분 수정
  woori-zip/src/app/user/(onboarding)/register/page.js
  woori-zip/src/components/domains/user/register/RegisterContent.js
Labels: ✨ Feature, 🌏 Deploy

#147 [DEPLOY] loading.js 파일 추가
  woori-zip/src/app/loading.js
  woori-zip/src/components/domains/user/login/LoginContent.js
Labels: ✨ Feature, 🌏 Deploy

#148 [DEPLOY] loading.js 파일 추가 후 병합
  woori-zip/src/app/loading.js
  woori-zip/src/components/domains/user/login/LoginContent.js
Labels: ✨ Feature, 🌏 Deploy

#156 [FEAT] 무한 스크롤 적용한 최근 본 대출 조회
  woori-zip/src/app/api/mypage/RecentlyLoanListAPI.js
  woori-zip/src/app/realestate/page.js
  woori-zip/src/components/domains/mypage/Tabs/Tabs.module.css
  woori-zip/src/components/domains/mypage/loan/LoanCard.js
  woori-zip/src/components/domains/mypage/loan/LoanCard.module.css
  woori-zip/src/components/domains/mypage/loan/hooks/useLoan.js
  woori-zip/src/components/domains/mypage/loan/loan.js
  woori-zip/src/components/domains/mypage/loan/loan.module.css
Labels: ✨ Feature

#158 [REFACTOR] 로그인 api 수정
  woori-zip/src/components/domains/user/login/LoginContent.js
  woori-zip/src/components/layout/Header/Header.js
  woori-zip/src/components/layout/Header/Header.module.css
Labels: 🌏 Deploy, ♻️ Refactor

#162 [FEAT] 중개사가 올린 집 조회 #157
  woori-zip/src/app/api/agent/UploadedPropertiesAPI.js
  woori-zip/src/components/domains/mypage/loan/loan.js
  woori-zip/src/components/domains/realsestate/UploadedProperties/PropertyCard.js
  woori-zip/src/components/domains/realsestate/UploadedProperties/PropertyCard.module.css
  woori-zip/src/components/domains/realsestate/UploadedProperties/UploadedProperties.js
  woori-zip/src/components/domains/realsestate/UploadedProperties/UploadedProperties.module.css
  woori-zip/src/components/domains/realsestate/UploadedProperties/hooks/useProperty.js
Labels: ✨ Feature

#177 [FEAT] 마이페이지 최근 본 대출
  woori-zip/src/components/domains/mypage/loan/LoanCard.module.css
Labels: ✨ Feature

#178 [FEAT] 지도페이지 상태 수정 및 메인페이지 수정
  woori-zip/public/assets/assistance.png
  woori-zip/public/assets/deposit.png
  woori-zip/public/assets/fund.png
  woori-zip/public/assets/isa.png
  woori-zip/public/assets/loan.png
  woori-zip/public/assets/room1.png
  woori-zip/public/assets/room2.png
  woori-zip/public/assets/room3.png
  woori-zip/public/assets/smartregister.png
  woori-zip/public/assets/trust.png
  woori-zip/public/assets/wonbanking.png
  woori-zip/src/app/page.js
  woori-zip/src/app/page.module.css
  woori-zip/src/components/domains/main/EnhancedGrid.js
  woori-zip/src/components/domains/main/EnhancedGrid.module.css
  woori-zip/src/components/domains/map/CategoryMenu.js
  woori-zip/src/components/domains/map/NavBar.js
  woori-zip/src/components/domains/map/NavBar.module.css
  woori-zip/src/components/layout/Header/Header.js
Labels: ✨ Feature, 🌏 Deploy

#182 [FEAT] 소비패턴분석 api 연결 수정
  woori-zip/src/app/analysis/page.js
  woori-zip/src/app/api/analysis/analysisAPI.js
  woori-zip/src/components/domains/analysis/analysis/Analysis.js
  woori-zip/src/components/domains/analysis/analysis/AnalysisDataLoader.js
  woori-zip/src/components/domains/analysis/analysis/AnalysisDataLoader.module.css
  woori-zip/src/components/domains/analysis/chat/Chat.js
  woori-zip/src/components/domains/analysis/search/AnalysisResult.js
  woori-zip/src/components/domains/analysis/search/AnalysisResult.module.css
  woori-zip/src/components/domains/analysis/search/InfrastructureSelector.js
  woori-zip/src/components/domains/analysis/search/InfrastructureSelector.module.css
  woori-zip/src/components/domains/analysis/search/RegionSelector.js
  woori-zip/src/components/domains/analysis/search/RegionSelector.module.css
  woori-zip/src/components/domains/analysis/search/Search.js
  woori-zip/src/components/domains/analysis/search/Search.module.css
Labels: ♻️ Refactor

#184 Feat/#180 중개사가 올린 집 조회
  woori-zip/src/app/api/agent/UploadedPropertiesAPI.js
  woori-zip/src/app/api/mypage/RecentlyLoanListAPI.js
  woori-zip/src/components/domains/mypage/Bookmarks/hooks/useBookMark.js
  woori-zip/src/components/domains/realsestate/UploadedProperties/PropertyCard.js
  woori-zip/src/components/domains/realsestate/UploadedProperties/PropertyCard.module.css
  woori-zip/src/components/domains/realsestate/UploadedProperties/UploadedProperties.js
  woori-zip/src/components/domains/realsestate/UploadedProperties/UploadedProperties.module.css
Labels: ✨ Feature

#193 [FEAT] 권한별 마이페이지 라우팅
  woori-zip/src/app/api/mypage/MypageAPI.js
  woori-zip/src/auth.js
  woori-zip/src/components/layout/Header/Header.js
Labels: ✨ Feature

#194 [FEAT] 지도페이지 수정 및 테스트 코드 추가
  woori-zip/.gitignore
  woori-zip/cypress.config.js
  woori-zip/cypress/e2e/analysis.cy.js
  woori-zip/cypress/e2e/home.cy.js
  woori-zip/cypress/e2e/login.cy.js
  woori-zip/cypress/e2e/map.cy.js
  woori-zip/cypress/e2e/mypage.cy.js
  woori-zip/cypress/support/commands.js
  woori-zip/cypress/support/e2e.js
  woori-zip/package-lock.json
  woori-zip/package.json
  woori-zip/src/app/api/map/houseApi.js
  woori-zip/src/components/domains/map/CategoryMenu.module.css
  woori-zip/src/components/domains/map/Latitude.js
  woori-zip/src/components/domains/map/MapPageContent.js
  woori-zip/src/components/domains/map/MapView.js
  woori-zip/src/components/domains/map/NavBar.js
  woori-zip/src/components/domains/map/PropertyList.js
Labels: ✨ Feature, 🌏 Deploy, ♻️ Refactor

#195 [MERGE] 지도페이지 수정 및 테스트 코드 추가 후 병합
  woori-zip/.gitignore
  woori-zip/cypress.config.js
  woori-zip/cypress/e2e/analysis.cy.js
  woori-zip/cypress/e2e/home.cy.js
  woori-zip/cypress/e2e/login.cy.js
  woori-zip/cypress/e2e/map.cy.js
  woori-zip/cypress/e2e/mypage.cy.js
  woori-zip/cypress/support/commands.js
  woori-zip/cypress/support/e2e.js
  woori-zip/package-lock.json
  woori-zip/package.json
  woori-zip/src/app/api/map/houseApi.js
  woori-zip/src/app/api/mypage/MypageAPI.js
  woori-zip/src/app/api/mypage/RecentlyLoanListAPI.js
  woori-zip/src/auth.js
  woori-zip/src/components/domains/main/EnhancedGrid.js
  woori-zip/src/components/domains/main/EnhancedGrid.module.css
  woori-zip/src/components/domains/map/CategoryMenu.module.css
  woori-zip/src/components/domains/map/Latitude.js
  woori-zip/src/components/domains/map/MapPageContent.js
  woori-zip/src/components/domains/map/MapView.js
  woori-zip/src/components/domains/map/NavBar.js
  woori-zip/src/components/domains/map/PropertyList.js
  woori-zip/src/components/layout/Header/Header.js
Labels: 🌏 Deploy, ♻️ Refactor

#196 [FEAT]: 로그 조회, 상세 조회 추가 및 회원 정보 조회 수정
  woori-zip/src/app/api/manager/managerAPI.js
  woori-zip/src/components/domains/manager/LogManagement/LogDetail.js
  woori-zip/src/components/domains/manager/LogManagement/LogDetail.module.css
  woori-zip/src/components/domains/manager/LogManagement/LogSearch.js
  woori-zip/src/components/domains/manager/LogManagement/LogSearch.module.css
  woori-zip/src/components/domains/manager/LogManagement/Modal.js
  woori-zip/src/components/domains/manager/LogManagement/Modal.module.css
  woori-zip/src/components/domains/manager/userManagement/MembersList/MembersList.js
Labels: ✨ Feature

#199 [FEAT] 라우팅 수정
  woori-zip/src/components/domains/main/PropertyGrid/PropertyGrid.js
  woori-zip/src/components/domains/main/PropertyGrid/PropertyGrid.module.css
  woori-zip/src/components/domains/map/PropertyDetails.js
  woori-zip/src/components/domains/mypage/Bookmarks/BookmarkCard.module.css
  woori-zip/src/components/domains/mypage/loan/LoanCard.js
  woori-zip/src/components/domains/mypage/loan/WebViewMyPageLoan.js
  woori-zip/src/components/domains/mypage/loan/WebViewMyPageLoan.module.css
  woori-zip/src/components/domains/user/login/LoginAdminPage.js
  woori-zip/src/components/domains/user/login/LoginAgentPage.js
Labels: ✨ Feature

#201 Feat/#189: 대출상품관리 수정 하기 초안
  woori-zip/src/app/api/manager/managerAPI.js
  woori-zip/src/components/domains/manager/LoanManagement/LoanView.js
  woori-zip/src/components/domains/manager/LoanManagement/LoanViewCard.js
  woori-zip/src/components/domains/manager/LoanManagement/LoanViewCard.module.css
  woori-zip/src/components/domains/manager/LoanManagement/modal/ChecklistEditModal.js
  woori-zip/src/components/domains/manager/LoanManagement/modal/ChecklistEditModal.module.css
  woori-zip/src/components/domains/manager/LoanManagement/modal/ChecklistModal.js
  woori-zip/src/components/domains/manager/LoanManagement/modal/ChecklistModal.module.css
  woori-zip/src/components/domains/manager/LoanManagement/modal/EditModal.js
  woori-zip/src/components/domains/manager/LoanManagement/modal/EditModal.module.css
  woori-zip/src/components/domains/manager/LoanManagement/modal/Modal.js
  woori-zip/src/components/domains/manager/LoanManagement/modal/Modal.module.css
Labels: ✨ Feature

#203 [FEAR]: 404 페이지, 로딩 페이지, 지도 오류 수정
  woori-zip/package-lock.json
  woori-zip/package.json
  woori-zip/src/app/api/map/houseApi.js
  woori-zip/src/app/loading-animation.json
  woori-zip/src/app/loading.js
  woori-zip/src/app/mypage/page.module.css
  woori-zip/src/app/not-found.js
  woori-zip/src/components/domains/main/EnhancedGrid.module.css
  woori-zip/src/components/domains/map/CategoryMenu.module.css
  woori-zip/src/components/domains/map/NavBar.js
  woori-zip/src/components/domains/map/NavBar.module.css
Labels: ✨ Feature

#205 [FEAT] 이미지 추가
  woori-zip/src/components/domains/loan/loanDetail/Detail.module.css
  woori-zip/src/components/domains/mypage/Bookmarks/BookmarkCard.module.css
  woori-zip/src/components/domains/mypage/MemberInfo/Member.js
  woori-zip/src/components/domains/mypage/MemberInfo/Member.module.css
  woori-zip/src/components/domains/mypage/loan/LoanCard.module.css
Labels: ✨ Feature

#206 [FEAT] 체크리스트 입력 수정 및 관리자 체크리스트 수정 #197
  woori-zip/src/app/api/manager/managerAPI.js
  woori-zip/src/components/atoms/BackButton.js
  woori-zip/src/components/atoms/button.png
  woori-zip/src/components/domains/loan/loanDetail/Detail.js
  woori-zip/src/components/domains/loan/loanDetail/Detail.module.css
  woori-zip/src/components/domains/loan/loanRecommendation/BottomCard.module.css
  woori-zip/src/components/domains/loan/loanRecommendation/WideCard.js
  woori-zip/src/components/domains/loan/loanRecommendation/WideCard.module.css
  woori-zip/src/components/domains/manager/LoanManagement/LoanView.js
  woori-zip/src/components/domains/manager/LoanManagement/LoanViewCard.js
  woori-zip/src/components/domains/manager/LoanManagement/modal/ChecklistEditModal.js
  woori-zip/src/components/domains/manager/LoanManagement/modal/ChecklistEditModal.module.css
  woori-zip/src/components/domains/manager/LoanManagement/modal/ChecklistModal.js
  woori-zip/src/components/domains/manager/LoanManagement/modal/Modal.module.css
  woori-zip/src/components/domains/mypage/loan/LoanCard.js
  woori-zip/src/components/domains/mypage/loan/LoanCard.module.css
Labels: ✨ Feature

#208 [FEAT] CSS 수정 및 관리자 추가버튼#197
  woori-zip/src/components/domains/loan/loanDetail/Detail.js
  woori-zip/src/components/domains/loan/loanDetail/Detail.module.css
  woori-zip/src/components/domains/loan/loanDetail/WebViewLoanDetail.js
  woori-zip/src/components/domains/loan/loanDetail/WebViewLoanDetail.module.css
  woori-zip/src/components/domains/manager/LoanManagement/LoanView.js
  woori-zip/src/components/domains/manager/LoanManagement/LoanView.module.css
  woori-zip/src/components/domains/manager/LoanManagement/LoanViewCard.module.css
  woori-zip/src/components/domains/manager/LoanManagement/modal/ChecklistEditModal.js
  woori-zip/src/components/domains/manager/LoanManagement/modal/ChecklistModal.js
Labels: ✨ Feature
